### ISSUE TITLE
Command hangs if bridge IP or username is incorrect

### ISSUE THREAD

**Issue by DCRichards** [bahamas10/hueadm#1]
## Issue

Running a command such as `hueadm lights` hangs if the user or bridge IP are incorrect. Instead, an error message should be shown, or the command should time out.

## Steps to replicate

Either create a `~/.hueadm.json` file or use `-H` `-U` with incorrect details and then run `hueadm lights`.

**Comment by bahamas10** [comment]
does it hang indefinitely for you? because the node HTTP timeout should kick in.  For example, if I use an IP address that is a server, but not a hue bridge I get ECONNREFUSED almost immediately

```
$ ./bin/hueadm -H 10.0.1.1 lights
error: Error: connect ECONNREFUSED
```

If I use an IP address that doesn't exist, I get ETIMEDOUT

```
$ time ./bin/hueadm -H 10.0.1.15 lights
error: Error: connect ETIMEDOUT

real	1m15.881s
user	0m0.135s
sys	0m0.031s
```

**Comment by bahamas10** [comment]
Closing this - feel free to reopen if you feel my response above was inadequate or incorrect.
