### ISSUE TITLE
Windows 10 - All working

### ISSUE THREAD

**Issue by sunscreem** [bahamas10/hueadm#2]
I'm being super lazy here as I really should PR the docs... anyway...

Installed this on windows 10. I had trouble running global node commands.  In the end I solved it by adding the node bin directory to my path and adding `.cmd` to the command.

The other issue was the `search` command didn't work. I had to find the IP of the hub from my router. 

Other than that - all good.

(The HEX colour codes are confusing though. I would have expected `#ffeeee` to have been white with a hint of red but its seems a bit more random. Probably user error).

Thank you for creating this.. seems like it took a lot of work.

**Comment by bahamas10** [comment]
Great, thanks for the insight!

I use the Windows Subsystem for Linux so I haven't run into any of the issues you've noticed above.  Interesting that `search` doesn't work - I'm not sure why that would be.

As far as hex values, the `hueadm` program itself converts hex to a value that hue can understand, so it's possible (and likely) that that conversion is lossy, and can result in some unexpected behaviors.

Glad everything else is working for you though!
