### ISSUE TITLE
How to apply scenes to groups?

### ISSUE THREAD

**Issue by neural-loop** [bahamas10/hueadm#6]
Is the show scene functionality just there to be able to get the json needed to set the state another way?

**Comment by bahamas10** [comment]
https://github.com/bahamas10/hueadm/pull/5

This was just merged in `v1.2.0`... check out the readme for more examples:

```
hueadm recall-scene <scene-id> <group-id>
-or-
hueadm group <group-id> scene=<scene-id>
```
